### ISSUE TITLE
How to update slider upon options change?

### ISSUE THREAD

**Issue by hjelmdal** [Splidejs/vue-splide#26]
Hi, 
I would like to control how many slides to show "perPage" upon viewport change. So I've done a handler updating the options ond Splide, and thought that there was an event detecting that called "updated" - but that event never gets fired, and I can't fire a refresh myself. The only method working for me from the api when using $refs is splide.go, otherwise I get splide.xxx is not a function :-(

Can anyone help me on what to do to make the slider refresh when I want it to?

Thanks in advance!

**Comment by solamichealolawale** [comment]
Why don't you try to use breakpoint to control the number of slides to show per page.

![image](https://user-images.githubusercontent.com/12444227/103643747-75acb780-4f55-11eb-818b-bf0969c35718.png)

For complete information about it, visit the link below
[Breakpoint  - https://splidejs.com/options/#breakpoints ](https://splidejs.com/options/#breakpoints)

**Comment by amb-jarek** [comment]
@solamichealolawale because it doesn't work.

For some reasons `breakpoints` do not work correctly in vue. When I resize browser window, no changes related to breakpoint setting are triggered. Then when I refresh page all breakpoint changes are applied.

I've added `window.addEventListener("resize", this.resizeHandler);` by myself and wanted to manually change Splide options but this doesn't work either.

Breakpoint setting are applied only on Splide initializaton.

**Comment by NaotoshiFujita** [comment]
In the latest version, responsive options become reactive:
https://splidejs.github.io/vue-splide/

Do not change readonly options:
https://splidejs.com/guides/options/#options
